name: Terraform

on:
  workflow_dispatch

jobs:
  terraform-job:
    runs-on: my-runner

    steps:
      - name: Install Terraform
        run: |
          #!/bin/bash
          sudo yum update -y
          sudo yum install -y yum-utils
          sudo yum-config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
          sudo yum -y install terraform
          terraform --version

      - name: Check version
        run: terraform --version   