name: Terraform

on:
  push:
    paths:
      - '.github/workflows/install.yml'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  terraform-job:
    runs-on: mine
    steps:
      - name: Check working directory
        run: pwd && ls

      - name: Clone repo
        uses: actions/checkout@v4

      - name: Create dummy tfstate
        run: touch terraform.tfstate

      - name: Git status
        run: git status

      - name: Upload Terraform State File
        uses: actions/upload-artifact@v4
        with:
          name: tfstate
          path: terraform.tfstate

  commit-job:
    needs: terraform-job
    runs-on: mine
    permissions:
      contents: write
    uses: ./.github/workflows/commit.yml
    with:
      filename: terraform.tfstate
