name: Create Blob storage manually

on:
  workflow_dispatch:
    inputs:
      resource_group_name:
        description: 'Azure Resource Group Name (e.g., blob_for_terraform)'
        required: true
      location:
        description: 'Azure Location (e.g., West Europe)'
        required: true
      storage_account_name:
        description: 'Storage Account Name (must be globally unique, e.g., maronaamrj)'
        required: true
      storage_account_tier:
        description: 'Storage Account Tier (e.g., Standard)'
        required: true
      replication_type:
        description: 'Replication Type (e.g., LRS)'
        required: true
      container_name:
        description: 'Storage Container Name (e.g., tfstate)'
        required: true
      container_access_type:
        description: 'Container Access Type (e.g., private)'
        required: true

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{ vars.AZ_APPID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZ_PASSWORD }}
      ARM_TENANT_ID: ${{ secrets.AZ_TENANT }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      TF_VAR_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      TF_VAR_resource_group_name: ${{ github.event.inputs.resource_group_name }}
      TF_VAR_location: ${{ github.event.inputs.location }}
      TF_VAR_storage_account_name: ${{ github.event.inputs.storage_account_name }}
      TF_VAR_storage_account_tier: ${{ github.event.inputs.storage_account_tier }}
      TF_VAR_replication_type: ${{ github.event.inputs.replication_type }}
      TF_VAR_container_name: ${{ github.event.inputs.container_name }}
      TF_VAR_container_access_type: ${{ github.event.inputs.container_access_type }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3


      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      - name: Terraform Init
        run: terraform init
        working-directory: .HCL/Blob/

      - name: Terraform Plan
        run: terraform plan
        working-directory: .HCL/Blob/

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: .HCL/Blob/
