name: Terraform Deploy with User Input

on:
  workflow_dispatch:
    inputs:
      resource_group_name:
        description: 'Azure Resource Group Name'
        required: true
        default: 'blob_for_terraform'
      location:
        description: 'Azure Location'
        required: true
        default: 'West Europe'
      storage_account_name:
        description: 'Storage Account Name (must be globally unique)'
        required: true
        default: 'maronaamrj'
      storage_account_tier:
        description: 'Storage Account Tier'
        default: 'Standard'
      replication_type:
        description: 'Replication Type'
        default: 'LRS'
      container_name:
        description: 'Storage Container Name'
        default: 'tfstate'
      container_access_type:
        description: 'Container Access Type'
        default: 'private'

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      TF_VAR_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      TF_VAR_resource_group_name: ${{ github.event.inputs.resource_group_name }}
      TF_VAR_location: ${{ github.event.inputs.location }}
      TF_VAR_storage_account_name: ${{ github.event.inputs.storage_account_name }}
      TF_VAR_storage_account_tier: ${{ github.event.inputs.storage_account_tier }}
      TF_VAR_replication_type: ${{ github.event.inputs.replication_type }}
      TF_VAR_container_name: ${{ github.event.inputs.container_name }}
      TF_VAR_container_access_type: ${{ github.event.inputs.container_access_type }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve
